version: "3.4"
# top level section with the 'x-' prefix
# which is the extension fields
#
x-logging: &default-logging
  options:
    max-size: "1m"
    max-file: "10"
    compress: "true"
  driver: "json-file"

services:

  # look at setup configuration details on https://hub.docker.com/_/postgres
  # for more customization
  db:
    image: "postgres:15.1-alpine"

    # anchor value injection 'default-logging' from x-logging
    logging: *default-logging
    container_name: "rxgithub-db"

    ports:

      # {host port}:{container port}
      # you can connect through 'localhost:54320'
      # port 5432 is the container port
      #
      - "54325:5432"

    volumes:
      # {host path}:{container path}
      #

      # this is where the pg data files will end up
      # specific the container $PGDATA path in environment
      #
      - rxgithub_db_data:/var/lib/postgresql/data/rxgithub

      # init build *.sql files go into your relative github-initdb.d
      # 'docker-entrypoint-initdb.d' is the container path that
      # postgres looks for build up *.sql files
      #
      - ./github-initdb.d:/docker-entrypoint-initdb.d
      - ./data:/pg/data

    environment:
      - PGDATA=/var/lib/postgresql/data/rxgithub
      - POSTGRES_PASSWORD=rx0bs-passw0rd

      # if you have a specific user use the below.
      # without the following the default root user is 'postgres'
      #
      # -POSTGRES_USER=
      # -POSTGRES_DB=
    command: ["postgres", "-c", "log_statement=all"]

volumes:

  # by adding to the top-level volumes
  # persist through the containers lifecycle even when stopped/removed
  # remove volume manually using 'docker volume rm'
  #
  rxgithub_db_data:
